<?php
define("HOST", ""); // YOUR HOST SITE/DATABASE INFORMATION GOES HERE
define("USER", ""); // YOUR HOST SITE/DATABASE INFORMATION GOES HERE
define("PASSWORD", ""); // YOUR HOST SITE/DATABASE INFORMATION GOES HERE
define("DATABASE", ""); // YOUR HOST SITE/DATABASE INFORMATION GOES HERE
define("CAN_REGISTER", "any");
define("DEFAULT_ROLE", "user");
define("SECURE", FALSE);    // FOR DEVELOPMENT ONLY
